/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CuDateQuery: typeof import('./../components/cu-date-query/index.vue')['default']
    CuDict: typeof import('./../components/cu-dict/index.vue')['default']
    CuDictLabel: typeof import('./../components/cu-dict-label/index.vue')['default']
    CuPicker: typeof import('./../components/cu-picker/index.vue')['default']
    DaTree: typeof import('./../components/da-tree/index.vue')['default']
    Loading1: typeof import('./../components/qiun-loading/loading1.vue')['default']
    Loading2: typeof import('./../components/qiun-loading/loading2.vue')['default']
    Loading3: typeof import('./../components/qiun-loading/loading3.vue')['default']
    Loading4: typeof import('./../components/qiun-loading/loading4.vue')['default']
    Loading5: typeof import('./../components/qiun-loading/loading5.vue')['default']
    QiunDataCharts: typeof import('./../components/qiun-data-charts/qiun-data-charts.vue')['default']
    QiunError: typeof import('./../components/qiun-error/qiun-error.vue')['default']
    QiunLoading: typeof import('./../components/qiun-loading/qiun-loading.vue')['default']
    TodoItem: typeof import('./../components/todo/TodoItem.vue')['default']
    TodoList: typeof import('./../components/todo/TodoList.vue')['default']
    /* 这些导入语句会导致整个 wot-design-uni 库被打包！ 这是问题的根源 */
    // 虽然这些是类型定义，但构建过程：
// 1. TypeScript 需要读取模块来获取类型信息
// 2. Webpack 在解析时无法区分"仅类型"导入
// 3. 最终会将整个模块包含在 bundle 中
//     WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
//     WdCalendar: typeof import('wot-design-uni')['Calendar']
//     WdCard: typeof import('wot-design-uni')['Card']
//     WdCell: typeof import('wot-design-uni')['Cell']
    // WdCellGroup: typeof import('wot-design-uni')['CellGroup']
    // WdCollapse: typeof import('wot-design-uni')['Collapse']
    // WdCollapseItem: typeof import('wot-design-uni')['CollapseItem']
    // WdDivider: typeof import('wot-design-uni')['Divider']
    // WdDropMenu: typeof import('wot-design-uni')['DropMenu']
    // WdDropMenuItem: typeof import('wot-design-uni')['DropMenuItem']
    // WdFab: typeof import('wot-design-uni')['Fab']
    // WdForm: typeof import('wot-design-uni')['Form']
    // WdGrid: typeof import('wot-design-uni')['Grid']
    // WdGridItem: typeof import('wot-design-uni')['GridItem']
    // WdIcon: typeof import('wot-design-uni')['Icon']
    // WdImg: typeof import('wot-design-uni')['Img']
    // WdImgCropper: typeof import('wot-design-uni')['ImgCropper']
    // WdInput: typeof import('wot-design-uni')['Input']
    // WdInputNumber: typeof import('wot-design-uni')['InputNumber']
    // WdLoadmore: typeof import('wot-design-uni')['Loadmore']
    // WdMessageBox: typeof import('wot-design-uni')['MessageBox']
    // WdNavbar: typeof import('wot-design-uni')['Navbar']
    // WdNoticeBar: typeof import('wot-design-uni')['NoticeBar']
    // WdPicker: typeof import('wot-design-uni')['Picker']
    // WdPopup: typeof import('wot-design-uni')['Popup']
    // WdRadio: typeof import('wot-design-uni')['Radio']
    // WdRadioGroup: typeof import('wot-design-uni')['RadioGroup']
    // WdSelectPicker: typeof import('wot-design-uni')['SelectPicker']
    // WdStatusTip: typeof import('wot-design-uni')['StatusTip']
    // WdSwiper: typeof import('wot-design-uni')['Swiper']
    // WdSwitch: typeof import('wot-design-uni')['Switch']
    // WdTag: typeof import('wot-design-uni')['Tag']
    // WdText: typeof import('wot-design-uni')['Text']
    // WdTextarea: typeof import('wot-design-uni')['Textarea']
    // WdToast: typeof import('wot-design-uni')['Toast']
    // WdUpload: typeof import('wot-design-uni')['Upload']
  }
}
